type obj =
  | Type of int (* Type i *)
  | Nat (* Nat *)
  | Var of string (* x *)
  | Zero (* zero *)
  | Succ of obj (* succ x *)
  | App of obj * obj (* M N *)
  | Fun of string * obj * obj (* fun (x:T) (y:T) ... (z:T).M *)
  | Pi of string * obj * obj (* pi (x:T) (y:T) ... (z:T).M *)
  (* There's a couple more *)
