name: CI build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  build:
    name: Continuous Intergration
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v3
      - name: setup OCaml
        run: |
          export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig
          opam init -a -j "$NJOBS" --compiler=ocaml-base-compiler.$COMPILER
          opam switch set ocaml-base-compiler.$COMPILER
          eval $(opam env)
          opam update
          opam install menhir
        env:
          COMPILER: "4.14.0"
          FINDLIB_VER: ".1.8.1"
          OPAMYES: "true"
          NJOBS: "2"
      - name: install Coq
        run: |
          opam pin add coq "$COQVER"
        env:
          COQVER: "8.16.1"
      - name: install Coq dependencies
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam update
          opam install coq-equations
          opam install coq-menhirlib
        env:
          OPAMYES: "true"
      - name: build lib
        run: |
          cd lib/
          make
