name: CI build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  OCAML_VER: "4.14.0"
  COQ_VER: "8.16.1"
      
jobs:
  build:
    name: Continuous Intergration
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v3
      - name: setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ env.OCAML_VER }}
      - name: install Menhir and Coq
        run: |
          opam update
          opam install menhir
          opam pin add coq "${{ COQ_VER }}"
      - name: install Coq dependencies
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam update
          opam install coq-equations
          opam install coq-menhirlib
        env:
          OPAMYES: "true"
      - name: build lib
        run: |
          cd lib/
          make
